# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # Use the official Bun setup action
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: bun install
      
      - name: Show project structure before build
        run: find . -type f -not -path "*/node_modules/*" -not -path "*/.git/*" | sort
      
      - name: Build
        run: bun run build
      
      - name: Debug build output
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing all directories:"
          find . -type d -maxdepth 2 | sort
          echo "Checking for dist directory:"
          if [ -d "./dist" ]; then
            echo "dist directory exists"
            echo "Contents of dist directory:"
            ls -la ./dist
          else
            echo "dist directory does not exist"
            echo "Checking build output in package.json:"
            grep -A 5 "\"build\"" package.json || echo "No build script found"
          fi
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the correct build output directory
          # If your build outputs to a different directory, change this path
          path: './dist'
          retention-days: 1
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
